=== sergiocuacor/LLMM/XML/Ejercicios PE/DTDs/Solución Ejercicios completos/dtd/ejercicio1.dtd
<!ELEMENT series (serie+) >
<!ELEMENT serie (titulo,temporadas,actorPrincipal,premios?)>
<!ATTLIST serie id ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT temporadas (#PCDATA) >
<!ELEMENT actorPrincipal (#PCDATA)>
<!ELEMENT premios (#PCDATA)>

=== sergiocuacor/LLMM/XML/Ejercicios PE/DTDs/Solución Ejercicios completos/xml/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE series SYSTEM "../dtd/ejercicio1.dtd">
<series>
    <serie id="d56225">
        <titulo>El cuento de la Criada</titulo>
        <temporadas>5</temporadas>
        <actorPrincipal>Elisabeth Moss</actorPrincipal>
        <premios>9</premios>
    </serie>
    <serie id="s234t">
        <titulo>Black Mirror</titulo>
        <temporadas>5</temporadas>
        <actorPrincipal>Bryce Dallas Howard</actorPrincipal>
    </serie>
</series>
