=== sergiocuacor/LLMM/XML/Ejercicios PE/DTDs/Solución Ejercicios completos/dtd/ejercicio2.dtd
<!ELEMENT paises (pais*)>
  <!ELEMENT pais ((idioma|capital)*)>
  <!ATTLIST pais nombre CDATA #REQUIRED poblacion CDATA #IMPLIED>
  <!ELEMENT idioma (#PCDATA)>
  <!ATTLIST idioma nacional (si|no) #IMPLIED>
  <!ELEMENT capital (#PCDATA)>

=== sergiocuacor/LLMM/XML/Completos/Ejercicios completos/Ejercicios completos/xml/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises SYSTEM "../dtd/ejercicio2.dtd">
<paises>
    <pais nombre="España" poblacion="47100396">
        <idioma nacional="si">Castellano</idioma>
        <idioma nacional="no">Euskera</idioma>
        <idioma nacional="no">Gallego</idioma>
        <capital>Madrid</capital>
    </pais>
    <pais nombre="Irlanda" poblacion="4857000">
        <idioma nacional="no">Irlandés</idioma>
        <idioma nacional="si">Inglés</idioma>
        <capital>Dublín</capital>
    </pais>
    <pais nombre="Portugal"/>
</paises>

=== sergiocuacor/LLMM/XML/Ejercicios PE/DTDs/Solución Ejercicios completos/xml/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises SYSTEM "../dtd/ejercicio2.dtd">
<paises>
    <pais poblacion="47100396" nombre="España">
        <idioma nacional="si">Castellano</idioma>
        <idioma nacional="no">Euskera</idioma>
        <idioma nacional="no">Gallego</idioma>
        <capital>Madrid</capital>
    </pais>
    <pais nombre="Irlanda" poblacion="4857000">
        <idioma nacional="si">Irlandés</idioma>
        <idioma nacional="si">Inglés</idioma>
        <capital>Dublín</capital>
    </pais>
    <pais nombre="Portugal"/>
</paises>
