=== sergiocuacor/LLMM/XML/Ejercicios PE/DTDs/Solución Ejercicios completos/dtd/ejercicio11.dtd
<!ELEMENT pacientes (paciente*)>
<!ELEMENT paciente (menores*,adultos*)>
<!ELEMENT menores (menor+)>
<!ELEMENT menor (nombre,apellidos,nombretutor,dnitutor,fechaNac,vacunas*)>
<!ELEMENT adultos (adulto+)>
<!ELEMENT adulto (dni,nombre,apellidos,fechaNac,(patologias)*)>
    <!ATTLIST adulto estadoLab (paro|activo|jubilado) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fechaNac (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombretutor (#PCDATA)>
<!ELEMENT dnitutor (#PCDATA)>

<!ELEMENT vacunas (vacuna+)>
<!ELEMENT vacuna (enfermedad,fechaVac)>
<!ELEMENT enfermedad (#PCDATA)>
<!ELEMENT fechaVac (#PCDATA)>

<!ELEMENT patologias (patologia+)>
<!ELEMENT patologia (tipo,fechaDiagnostico,tratamiento?)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT fechaDiagnostico (#PCDATA)>
<!ELEMENT tratamiento (#PCDATA)>

=== sergiocuacor/LLMM/XML/Ejercicios PE/DTDs/Solución Ejercicios completos/xml/ejercicio11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pacientes SYSTEM "../dtd/ejercicio11.dtd">
<pacientes>
    <paciente>
        <menores>
            <menor>
                <nombre>Pepito</nombre>
                <apellidos>Perez</apellidos>
                <nombretutor>Juan</nombretutor>
                <dnitutor>47612398u</dnitutor>
                <fechaNac>21/03/2019</fechaNac>
            </menor>
        </menores>
        <adultos>
            <adulto estadoLab="jubilado">
                <dni>38912480f</dni>
                <nombre>Ana</nombre>
                <apellidos>Gomez</apellidos>
                <fechaNac>31/12/1945</fechaNac>
                <patologias>
                    <patologia>
                        <tipo>Cardiopat√≠a</tipo>
                        <fechaDiagnostico>13/02/2012</fechaDiagnostico>
                    </patologia>
                </patologias>
            </adulto>
        </adultos>
    </paciente>
</pacientes>
