=== sergiocuacor/LLMM/XML/ejemplosDTDs/ejemplosDTDs/dtd/ejemploEmail.dtd
<!ELEMENT email (para,cc?,cco?,asunto,cuerpo)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cco (#PCDATA)>
<!ELEMENT asunto (fecha,texto)>
<!ELEMENT cuerpo (fecha,texto)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT texto (#PCDATA)>

=== sergiocuacor/LLMM/XML/ejemplosDTDs/ejemplosDTDs/xml/ejemploEmail.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email SYSTEM "../dtd/ejemploEmail.dtd">
<email>
    <para> Elena Marcos </para>
    <asunto>
        <fecha></fecha>
        <texto> </texto>
    </asunto>
    <cuerpo>
        <fecha> </fecha>
        <texto></texto>
    </cuerpo>

</email>
