=== sergiocuacor/LLMM/XML/ejemplosDTDs/ejemplosDTDs/dtd/ejemplo1.dtd
<!ELEMENT asignaturas (asignatura*)>
<!ELEMENT asignatura (alumnos,profesores)>
<!ATTLIST asignatura
    codigo ID #REQUIRED>
<!ELEMENT alumnos (alumno)+>
<!ELEMENT profesores (profesor)+>
<!ELEMENT alumno (nombre,apellido,numTelefono)>
<!ELEMENT profesor (nombre,apellido,antiguedad)>
<!ATTLIST profesor
  codAsignaturas IDREFS #REQUIRED
  numEmpleado ID #REQUIRED>
<!ELEMENT numTelefono (#PCDATA)>
<!ELEMENT antiguedad (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>

=== sergiocuacor/LLMM/XML/ejemplosDTDs/ejemplosDTDs/xml/ejemplo1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE asignaturas SYSTEM "../dtd/ejemplo1.dtd">
<asignaturas>
<!-- El elemento asignatura(con sus descendentes) se repetiría tantas veces como asignaturas hubiera-->
    <asignatura codigo="Asig1">
        <alumnos>
        <!-- Dentro de alumnos se incluirían tantos elementos alumno como alumnos tuviera la asignatura-->
            <alumno>
                <nombre>Elena</nombre>
                <apellido>Marcos</apellido>
                <numTelefono>456753247</numTelefono>
            </alumno>
        </alumnos>
        <profesores>
        <!-- Dentro de profesores se incluirían tantos elementos profesor como profesores tuviera la asignatura-->
            <profesor numEmpleado="E23456" codAsignaturas="Asig1">
                <nombre>Sonia</nombre>
                <apellido>Gutiérrez</apellido>
                <antiguedad>1</antiguedad>
            </profesor>
        </profesores>
    </asignatura>
</asignaturas>
