=== sergiocuacor/LLMM/XML/Ejercicios PE/ex2021/Examen/ej1.dtd
<!ELEMENT socios (socio+)>
<!ELEMENT socio (nombre, dni?,telefono,direccion+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

=== sergiocuacor/LLMM/XML/Ejercicios PE/ex2021/Examen/ej1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socios SYSTEM "./ej1.dtd">
<socios>
    <socio>
        <nombre>Manue</nombre>
        <dni>849284M</dni>
        <telefono>7847284</telefono>
        <direccion>Calle medina 3</direccion>
        <direccion>Calle azulejo76</direccion>

    </socio>
    <socio>
        <nombre>alfred</nombre>
        <telefono>8439842</telefono>
        <direccion>calle karma 6</direccion>
    </socio>
</socios>
