=== sergiocuacor/LLMM/XML/Tema/schema/TiposComplejos/xsd/ejercicio10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- TIPOS SIMPLES-->
    <xsd:simpleType name="tipoCodAlumno">
        <xsd:restriction base="xsd:ID">
            <xsd:pattern value="[A-Za-z]{3}\d{2}"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoGraduado">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="si"></xsd:enumeration>
            <xsd:enumeration value="no"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- TIPOS COMPLEJOS -->
    <xsd:complexType name="tipoAlumno">
        <xsd:sequence>
            <xsd:element name="nombre" type="xsd:string"></xsd:element>
            <xsd:element name="apellidos" type="xsd:string"></xsd:element>
            <xsd:element name="modulo" type="xsd:string"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="codAlumno" type="tipoCodAlumno"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tipoAntiguoAlumno">
        <xsd:complexContent>
            <xsd:extension base="tipoAlumno">
                <xsd:sequence>
                    <xsd:element name="fechaFin" type="xsd:date"></xsd:element>
                </xsd:sequence>
                <xsd:attribute name="graduado" type="tipoGraduado" use="required"></xsd:attribute>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>




<!-- ====================================================================================================================================================-->
    
    <xsd:element name="alumnos">

        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="alumno" type="tipoAlumno" maxOccurs="unbounded"></xsd:element>
                <xsd:element name="antiguoAlumno" type="tipoAntiguoAlumno"
                    maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    
    </xsd:element>
</xsd:schema>

=== sergiocuacor/LLMM/XML/Tema/schema/TiposComplejos/xml/ejercicio10.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/ejercicio10.xsd">

    <alumno>
        <nombre>Sergio</nombre>
        <apellidos>Cuadrado</apellidos>
        <modulo>DAW</modulo>
    </alumno>
    <alumno>
        <nombre>Sergio</nombre>
        <apellidos>Cuadrado</apellidos>
        <modulo>DAW</modulo>
    </alumno>
    <alumno>
        <nombre>Sergio</nombre>
        <apellidos>Cuadrado</apellidos>
        <modulo>DAW</modulo>
    </alumno>
    <antiguoAlumno codAlumno="LLA33" graduado="si">
        <nombre>djkfs</nombre>
        <apellidos>fsjfhsjd</apellidos>
        <modulo>fjskf</modulo>
        <fechaFin>2024-05-13</fechaFin>
    </antiguoAlumno>

</alumnos>
